name: Automated RDD Generation

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  build: # job 1
    name: 'Generate RDD'
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'

    strategy:
        matrix:
            build-number: ['14.0']

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate RDD
        run: |
          export ZENHUB_TOKEN=${{ secrets.ZENHUB_TOKEN }}
          pds-issues --token ${{ secrets.ADMIN_GITHUB_TOKEN }} --format rst --issue_state closed --build B${{matrix.build-number}}
          mkdir -p docs/source/releases/${{matrix.build-number}}
          mv pdsen_issues.rst docs/source/releases/${{matrix.build-number}}/rdd.rst

      - name: Make Sphinx
        id: make
        run: |
          cd docs
          make github
          cd ..

      - name: Push LDDs to Github
        run: |
          git config --local user.email "pdsen-ci@jpl.nasa.gov"
          git config --local user.name "PDSEN CI Bot"
          git add -A .
          git commit --allow-empty -m "Auto-generated RDD by PDSEN CI Bot"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
